"""Explore Graph — merged Graph Query (NL-to-Cypher) + Graph Visualization."""

import math
import streamlit as st
import plotly.graph_objects as go
import pandas as pd
import numpy as np

from app.services.neo4j_client import BackendClient


def page_graph_explore(client: BackendClient):
    st.markdown("## 🕸️ Explore Graph")
    st.caption("Query and visualize the NCIT/caDSR knowledge graph.")

    is_live = client.connected

    tab_query, tab_viz = st.tabs(["🔍 Natural Language Query", "🕸️ Visualization"])

    # ═══════════════════════════════════════════════════════════════════
    # TAB 1: NL-to-Cypher Query
    # ═══════════════════════════════════════════════════════════════════
    with tab_query:
        status_cols = st.columns(3)
        with status_cols[0]:
            if is_live:
                st.success("Neo4j: Connected", icon="✅")
            else:
                st.error("Neo4j: Offline", icon="❌")
        with status_cols[1]:
            openai_ok = client.openai_ready
            if openai_ok:
                st.success("OpenAI: Connected", icon="🤖")
            else:
                st.warning("OpenAI: Offline (pattern fallback)", icon="⚠️")
        with status_cols[2]:
            st.info("Queries generated & executed live", icon="🔍")

        with st.expander("⚙️ NL-to-Cypher System Prompt", expanded=False):
            nl_prompt = st.text_area(
                "Prompt",
                value=st.session_state.get("_nl_prompt", client.GRAPH_SCHEMA_PROMPT),
                height=200,
                key="nl_cypher_prompt",
            )
            pc1, pc2 = st.columns([1, 5])
            with pc1:
                if st.button("💾 Save", key="save_nl_prompt"):
                    st.session_state["_nl_prompt"] = nl_prompt
                    st.success("Prompt saved!")
            with pc2:
                if st.button("↩️ Reset", key="reset_nl_prompt"):
                    st.session_state["_nl_prompt"] = client.GRAPH_SCHEMA_PROMPT
                    st.rerun()

        st.markdown("**Try these examples:**")
        examples = [
            "How many synonyms are there for C1234?",
            "Show me all synonyms for 'Lung Carcinoma'",
            "What CDEs use the concept C4878?",
            "Find permissible values related to prostate",
            "List NCIT concepts with 'diabetes' in the name",
        ]
        ex_cols = st.columns(len(examples))
        for i, ex in enumerate(examples):
            with ex_cols[i]:
                if st.button(f"💡 {ex[:30]}...", key=f"ex_{i}", use_container_width=True):
                    st.session_state["_gq_question"] = ex
                    st.rerun()

        question = st.text_input(
            "Your question",
            value=st.session_state.get("_gq_question", ""),
            placeholder="e.g. How many synonyms are there for C1234?",
            key="graph_query_input",
        )

        if st.button("🚀 Run Query", type="primary", disabled=not question.strip()):
            c_model = st.session_state.get("cypher_model", "llama3.1")
            with st.spinner(f"Generating Cypher via {c_model}..."):
                prompt_to_use = st.session_state.get("_nl_prompt", None)
                result = client.nl_to_cypher(question, system_prompt=prompt_to_use, cypher_model=c_model)
            st.session_state.graph_query_history.insert(0, result)
            if "_gq_question" in st.session_state:
                del st.session_state["_gq_question"]

        if st.session_state.graph_query_history:
            latest = st.session_state.graph_query_history[0]
            st.markdown("---")

            if latest["method"] == "openai":
                st.success("🤖 Cypher generated by **OpenAI**")
            else:
                st.info("🔧 Cypher generated by **pattern-based fallback**")

            st.code(latest["cypher"], language="cypher")
            if latest.get("error"):
                st.warning(f"⚠️ {latest['error']}")
            if latest["results"]:
                df = pd.DataFrame(latest["results"])
                st.dataframe(df, use_container_width=True, hide_index=True)
                st.download_button("📥 CSV", df.to_csv(index=False), "graph_query_results.csv")
            elif not latest.get("error"):
                st.info("No results returned.")

            with st.expander("✏️ Edit & re-run Cypher manually"):
                edited = st.text_area("Cypher", value=latest["cypher"], height=100, key="edit_cypher")
                if st.button("▶️ Execute", key="rerun_edited"):
                    rows = client.run_cypher(edited)
                    if rows:
                        st.dataframe(pd.DataFrame(rows), use_container_width=True, hide_index=True)
                    else:
                        st.info("No results")

        if len(st.session_state.graph_query_history) > 1:
            with st.expander(f"📜 Query History ({len(st.session_state.graph_query_history)})"):
                for i, h in enumerate(st.session_state.graph_query_history):
                    icon = "🤖" if h["method"] == "openai" else "🔧"
                    st.markdown(f"**{i+1}.** {icon} {h['question']}")
                    st.code(h["cypher"], language="cypher")
                    if h["results"]:
                        st.caption(f"→ {h['total']} results")
                    if h.get("error"):
                        st.caption(f"⚠️ {h['error']}")
                    st.markdown("---")

    # ═══════════════════════════════════════════════════════════════════
    # TAB 2: Graph Visualization
    # ═══════════════════════════════════════════════════════════════════
    with tab_viz:
        main_col, side_col = st.columns([3, 1])

        with side_col:
            if is_live:
                st.success("Live Neo4j graph", icon="🔗")
                center_term = st.text_input("Center node (term)", placeholder="e.g. Lung Carcinoma")
                limit = st.slider("Max nodes", 10, 200, 50, step=10)
            else:
                st.warning("Mock graph (Neo4j offline)")
                center_term = ""
                limit = 50

            layout_type = st.selectbox("Layout", ["Force-directed", "Circular", "Hierarchical", "Random"])
            search_term = st.text_input("🔍 Search nodes", key="viz_search")

            with st.expander("Cypher Query Builder"):
                cypher = st.text_area("Query", "MATCH (n)-[r]->(m) RETURN n, r, m LIMIT 25", height=100)
                if is_live and st.button("▶ Run Cypher", key="viz_cypher_run"):
                    raw = client.run_cypher(cypher)
                    if raw:
                        st.json(raw[:10])
                    else:
                        st.info("No results")

        with main_col:
            if is_live:
                with st.spinner("Loading graph from Neo4j..."):
                    payload = client.fetch_graph_neighbourhood(center_term=center_term or "", limit=limit)
                nodes = payload.nodes
                edges = payload.edges
                if not nodes:
                    st.info("No nodes returned. Try a different center term.")
            else:
                nodes, edges = _generate_mock_graph(limit)

            if not nodes:
                return

            positions = _compute_positions(nodes, layout_type)
            fig = _build_plotly_figure(nodes, edges, positions, search_term)
            st.plotly_chart(fig, use_container_width=True)

            # Legend
            type_colors = {}
            for n in nodes:
                t = n.get("type", "Unknown")
                if t not in type_colors:
                    type_colors[t] = n.get("color", "#607d8b")
            legend_cols = st.columns(min(len(type_colors), 6))
            for i, (tp, col) in enumerate(type_colors.items()):
                with legend_cols[i % len(legend_cols)]:
                    st.markdown(
                        f'<span style="display:inline-block;width:10px;height:10px;'
                        f'border-radius:50%;background:{col};margin-right:4px;"></span> {tp}',
                        unsafe_allow_html=True,
                    )


# ── Helpers ────────────────────────────────────────────────────────────

def _generate_mock_graph(n):
    type_colors = {"Person": "#4fc3f7", "Document": "#4caf50", "Concept": "#ff9800", "Organization": "#9c27b0"}
    types = list(type_colors.keys())
    np.random.seed(42)
    nodes = [{"name": f"{types[i%4]}_{i+1}", "type": types[i%4], "color": type_colors[types[i%4]]} for i in range(min(n, 50))]
    edges = []
    for i in range(len(nodes)):
        for _ in range(min(3, np.random.randint(1, 4))):
            j = np.random.randint(0, len(nodes))
            if i != j:
                src, tgt = nodes[i]["name"], nodes[j]["name"]
                if not any(e["source"] == src and e["target"] == tgt for e in edges):
                    edges.append({"source": src, "target": tgt, "similarity": np.random.random()})
    return nodes, edges


def _compute_positions(nodes, layout_type):
    positions = {}
    n = len(nodes)
    if layout_type == "Circular":
        for i, nd in enumerate(nodes):
            angle = 2 * math.pi * i / max(n, 1)
            positions[nd["name"]] = (math.cos(angle), math.sin(angle))
    elif layout_type == "Hierarchical":
        levels = 4
        per_level = max(1, n // levels)
        for i, nd in enumerate(nodes):
            lv = i // per_level
            pos = i % per_level
            positions[nd["name"]] = ((pos * 2.0) / max(per_level, 1) - 1, 1 - (lv * 2.0) / levels)
    elif layout_type == "Force-directed":
        np.random.seed(hash(str(n)) % 2**31)
        for nd in nodes:
            positions[nd["name"]] = ((np.random.random() - 0.5) * 4, (np.random.random() - 0.5) * 4)
        for _ in range(8):
            names = list(positions.keys())
            for i in range(len(names)):
                for j in range(i + 1, len(names)):
                    a = list(positions[names[i]])
                    b = list(positions[names[j]])
                    dx, dy = a[0] - b[0], a[1] - b[1]
                    dist = math.sqrt(dx * dx + dy * dy) + 0.01
                    if dist < 1:
                        force = (1 - dist) * 0.05
                        a[0] += (dx / dist) * force
                        a[1] += (dy / dist) * force
                        b[0] -= (dx / dist) * force
                        b[1] -= (dy / dist) * force
                    positions[names[i]] = tuple(a)
                    positions[names[j]] = tuple(b)
    else:  # Random
        np.random.seed(42)
        for nd in nodes:
            positions[nd["name"]] = ((np.random.random() - 0.5) * 3, (np.random.random() - 0.5) * 3)
    return positions


def _build_plotly_figure(nodes, edges, positions, search_term):
    fig = go.Figure()

    name_to_pos = {n["name"]: positions.get(n["name"], (0, 0)) for n in nodes}
    edge_x, edge_y = [], []
    for e in edges:
        if e["source"] in name_to_pos and e["target"] in name_to_pos:
            x0, y0 = name_to_pos[e["source"]]
            x1, y1 = name_to_pos[e["target"]]
            edge_x += [x0, x1, None]
            edge_y += [y0, y1, None]
    fig.add_trace(go.Scatter(
        x=edge_x, y=edge_y, mode="lines",
        line=dict(width=1, color="rgba(180,180,180,0.25)"),
        hoverinfo="none", showlegend=False,
    ))

    highlighted = [
        n["name"] for n in nodes
        if search_term and search_term.lower() in n["name"].lower()
    ] if search_term else []

    fig.add_trace(go.Scatter(
        x=[positions[n["name"]][0] for n in nodes],
        y=[positions[n["name"]][1] for n in nodes],
        mode="markers+text",
        text=[n["name"] for n in nodes],
        textposition="top center",
        hovertext=[f'{n["name"]} ({n.get("type","")})' for n in nodes],
        hoverinfo="text",
        marker=dict(
            size=[18 if n["name"] in highlighted else 12 for n in nodes],
            color=[n.get("color", "#607d8b") for n in nodes],
            line=dict(
                width=[3 if n["name"] in highlighted else 1 for n in nodes],
                color=["#22d3ee" if n["name"] in highlighted else "#fff" for n in nodes],
            ),
        ),
        textfont=dict(size=8, color="#374151"),
        showlegend=False,
    ))

    fig.update_layout(
        height=600, showlegend=False,
        xaxis=dict(showgrid=False, zeroline=False, showticklabels=False),
        yaxis=dict(showgrid=False, zeroline=False, showticklabels=False),
        margin=dict(l=0, r=0, t=0, b=0),
        paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)",
        hovermode="closest",
    )

    if search_term and highlighted:
        st.info(f"Found **{len(highlighted)}** matching nodes: {', '.join(highlighted[:8])}")

    return fig
